### PR TITLE
Fixes for  returning object name, password length, userStatus to userRole

### LINKED ISSUE #1: Corrections for returning object in mutation
# Background
 - Corrections for signing up and creating user
 - Password length should be minimun six

# To Do
- [ ] To be the same name for returning object user and token in mutation
 (signUpReturn and AuthPayload ....)
image

- [ ] To change field name as `role` instead of using `userStatus`
image

- [ ] To check password length when creating user
image

### PR DESCRIPTION
**Pull request by scm-khinekhineoo**
# What is fixes

- [x]  fixes return object's name 
- [x]  validate password length in signUp and userCreate process.
- [x]  change users table's field [userStatus] to [userRole]

# References
Fixes #1

### CODE REVIEW

File: models/user.js [hunk 1]
```diff
@@ -185,12 +193,23 @@ class UserModel extends AbstractModel {
...
       }
       this.password = await CustomUtils.hashPassword(params.newPassword);
       return this.constructor.toModel(this);
     }
 
+    static async validatePassword(password) {
+      const messages = [];
+      messages.push(
+        ...CustomValidator.validateString("Password", password, {
+          min: 8,
```
Comment (AyeSuPaing-ASP) [inline models/user.js]: @khinekhineoo21 
I'd like to request you to use only `min` coz ```password``` can be more than 20.
Thank you.

File: models/user.js [hunk 2]
```diff
@@ -306,7 +325,7 @@ UserModel.authStatus = {
   noAuth: 0    
 }
   
-UserModel.userStatus = {
+UserModel.userRole = {
```
Comment (AyeSuPaing-ASP) [inline models/user.js]: Please use the name `role` instead of using `userRole`.

File: schema.graphql [hunk 3]
```diff
@@ -32,16 +32,21 @@ type User {
   username: String
   authStatus: Int
   suspendStatus: Int
-  userStatus: Int
+  userRole: Int
```
Comment (AyeSuPaing-ASP) [inline schema.graphql]: I thint that it would be better using variable name **role** than **userRole**.

**Review by AyeSuPaing-ASP — CHANGES_REQUESTED** [review]

**Review by AyeSuPaing-ASP — APPROVED** [review]
LGTM! Thank you.
